---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install dependences
  - pip install ansible nose coveralls mock requests flake8

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  
  # NIFCLOUD modules check
  - nosetests --no-byte-compile --with-coverage --cover-package=library/ --where=library/
  - coveralls
  - flake8 library/*.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
