---
# file: tasks/centos.yml

- name: Import EPEL GPG Key (for CentOS)
  run_once: true
  local_action:
    module: rpm_key
    key: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

- name: Check EPEL repository (for CentOS)
  run_once: true
  local_action:
    module: yum
    name: epel-release
    state: present
  register: niftycloud_check_epel_results
  ignore_errors: yes

- name: Add EPEL repository (for CentOS)
  run_once: true
  local_action:
    module: yum
    name: "https://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: niftycloud_check_epel_results|failed

- name: Install python-pip (for CentOS)
  run_once: true
  become: yes
  local_action:
    module: yum
    name: python-pip
