---
# file: tasks/main.yml

- name: Gathering facts from localhost
  run_once: true
  local_action:
    module: setup

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install "Requests" python package
  run_once: true
  become: yes
  local_action:
    module: pip
    name: requests
    version: 2.5.3
